export const cardsData = [
  //PLAYING CARD  OF SPADES
  {
    id: 1,
    uniCode: "U+1F0A1",
    htmlCode: "127137",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/PLAYING_CARD_ACE_OF_SPADES.svg/449px-PLAYING_CARD_ACE_OF_SPADES.svg.png",
  },
  {
    id: 2,
    uniCode: "U+1F0A2",
    htmlCode: "(127138)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/PLAYING_CARD_TWO_OF_SPADES.svg/449px-PLAYING_CARD_TWO_OF_SPADES.svg.png",
  },

  {
    id: 3,
    uniCode: "U+1F0A3",
    htmlCode: "(127139)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/PLAYING_CARD_THREE_OF_SPADES.svg/449px-PLAYING_CARD_THREE_OF_SPADES.svg.png",
  },
  {
    id: 4,
    uniCode: "U+1F0A4",
    htmlCode: "(127140)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/PLAYING_CARD_FOUR_OF_SPADES.svg/449px-PLAYING_CARD_FOUR_OF_SPADES.svg.png",
  },
  {
    id: 5,
    uniCode: "U+1F0A5",
    htmlCode: "(127141)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/PLAYING_CARD_FIVE_OF_SPADES.svg/449px-PLAYING_CARD_FIVE_OF_SPADES.svg.png",
  },
  {
    id: 6,
    uniCode: "U+1F0A6",
    htmlCode: "(127142)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/PLAYING_CARD_SIX_OF_SPADES.svg/449px-PLAYING_CARD_SIX_OF_SPADES.svg.png",
  },
  {
    id: 7,
    uniCode: "U+1F0A7",
    htmlCode: "(127143)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/PLAYING_CARD_SEVEN_OF_SPADES.svg/449px-PLAYING_CARD_SEVEN_OF_SPADES.svg.png",
  },
  {
    id: 8,
    uniCode: "U+1F0A8",
    htmlCode: "(127144)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/PLAYING_CARD_EIGHT_OF_SPADES.svg/449px-PLAYING_CARD_EIGHT_OF_SPADES.svg.png",
  },
  {
    id: 9,
    uniCode: "U+1F0A9",
    htmlCode: "(127145)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/PLAYING_CARD_NINE_OF_SPADES.svg/449px-PLAYING_CARD_NINE_OF_SPADES.svg.png",
  },
  {
    id: 10,
    uniCode: "U+1F0AA",
    htmlCode: "(127146)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/PLAYING_CARD_TEN_OF_SPADES.svg/449px-PLAYING_CARD_TEN_OF_SPADES.svg.png",
  },
  {
    id: 11,
    uniCode: "U+1F0AB",
    htmlCode: "(127147)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/PLAYING_CARD_JACK_OF_SPADES.svg/449px-PLAYING_CARD_JACK_OF_SPADES.svg.png",
  },
  {
    id: 12,
    uniCode: "U+1F0AD",
    htmlCode: "(127149)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/PLAYING_CARD_QUEEN_OF_SPADES.svg/449px-PLAYING_CARD_QUEEN_OF_SPADES.svg.png",
  },
  {
    id: 13,
    uniCode: "U+1F0AE",
    htmlCode: "(127150)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/PLAYING_CARD_KING_OF_SPADES.svg/449px-PLAYING_CARD_KING_OF_SPADES.svg.png",
  },

  // PLAYING CARD  OF HEARTS
  {
    id: 1,
    uniCode: "U+1F0B1",
    htmlCode: "(127153)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/PLAYING_CARD_ACE_OF_HEARTS.svg/449px-PLAYING_CARD_ACE_OF_HEARTS.svg.png",
  },
  {
    id: 2,
    uniCode: "U+1F0B2",
    htmlCode: "(127154)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/PLAYING_CARD_TWO_OF_HEARTS.svg/449px-PLAYING_CARD_TWO_OF_HEARTS.svg.png",
  },
  {
    id: 3,
    uniCode: "U+1F0B3",
    htmlCode: "(127155)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/PLAYING_CARD_THREE_OF_HEARTS.svg/449px-PLAYING_CARD_THREE_OF_HEARTS.svg.png",
  },
  {
    id: 4,
    uniCode: "U+1F0B4",
    htmlCode: "(127156)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/PLAYING_CARD_FOUR_OF_HEARTS.svg/449px-PLAYING_CARD_FOUR_OF_HEARTS.svg.png",
  },
  {
    id: 5,
    uniCode: "U+1F0B5",
    htmlCode: "(127157)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/PLAYING_CARD_FIVE_OF_HEARTS.svg/449px-PLAYING_CARD_FIVE_OF_HEARTS.svg.png",
  },
  {
    id: 6,
    uniCode: "U+1F0B6",
    htmlCode: "(127158)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/PLAYING_CARD_SIX_OF_HEARTS.svg/449px-PLAYING_CARD_SIX_OF_HEARTS.svg.png",
  },
  {
    id: 7,
    uniCode: "U+1F0B7",
    htmlCode: "(127159)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/PLAYING_CARD_SEVEN_OF_HEARTS.svg/449px-PLAYING_CARD_SEVEN_OF_HEARTS.svg.png",
  },
  {
    id: 8,
    uniCode: "U+1F0B8",
    htmlCode: "(127160)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/PLAYING_CARD_EIGHT_OF_HEARTS.svg/449px-PLAYING_CARD_EIGHT_OF_HEARTS.svg.png",
  },
  {
    id: 9,
    uniCode: "U+1F0B9",
    htmlCode: "(127161)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/PLAYING_CARD_NINE_OF_HEARTS.svg/449px-PLAYING_CARD_NINE_OF_HEARTS.svg.png",
  },
  {
    id: 10,
    uniCode: "U+1F0BA",
    htmlCode: "(127162)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PLAYING_CARD_TEN_OF_HEARTS.svg/449px-PLAYING_CARD_TEN_OF_HEARTS.svg.png",
  },
  {
    id: 11,
    uniCode: "U+1F0BB",
    htmlCode: "(127163)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/PLAYING_CARD_JACK_OF_HEARTS.svg/449px-PLAYING_CARD_JACK_OF_HEARTS.svg.png",
  },
  {
    id: 12,
    uniCode: "U+1F0BD",
    htmlCode: "(127165)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/PLAYING_CARD_QUEEN_OF_HEARTS.svg/449px-PLAYING_CARD_QUEEN_OF_HEARTS.svg.png",
  },
  {
    id: 13,
    uniCode: "U+1F0BE",
    htmlCode: "(127166)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/PLAYING_CARD_KING_OF_HEARTS.svg/449px-PLAYING_CARD_KING_OF_HEARTS.svg.png",
  },
  // PLAYING CARD  OF DIAMONDS
  {
    id: 1,
    uniCode: "U+1F0C1",
    htmlCode: "(127169)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/PLAYING_CARD_ACE_OF_DIAMONDS.svg/449px-PLAYING_CARD_ACE_OF_DIAMONDS.svg.png",
  },
  {
    id: 2,
    uniCode: "U+1F0C2",
    htmlCode: "(127170)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/PLAYING_CARD_TWO_OF_DIAMONDS.svg/449px-PLAYING_CARD_TWO_OF_DIAMONDS.svg.png",
  },
  {
    id: 3,
    uniCode: "U+1F0C3",
    htmlCode: "(127171)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/PLAYING_CARD_THREE_OF_DIAMONDS.svg/449px-PLAYING_CARD_THREE_OF_DIAMONDS.svg.png",
  },
  {
    id: 4,
    uniCode: "U+1F0C4",
    htmlCode: "(127172)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/PLAYING_CARD_FOUR_OF_DIAMONDS.svg/449px-PLAYING_CARD_FOUR_OF_DIAMONDS.svg.png",
  },
  {
    id: 5,
    uniCode: "U+1F0C5",
    htmlCode: "(127173)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/PLAYING_CARD_FIVE_OF_DIAMONDS.svg/449px-PLAYING_CARD_FIVE_OF_DIAMONDS.svg.png",
  },
  {
    id: 6,
    uniCode: "U+1F0C6",
    htmlCode: "(127174)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/PLAYING_CARD_SIX_OF_DIAMONDS.svg/449px-PLAYING_CARD_SIX_OF_DIAMONDS.svg.png",
  },
  {
    id: 7,
    uniCode: "U+1F0C7",
    htmlCode: "(127175)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/PLAYING_CARD_SEVEN_OF_DIAMONDS.svg/449px-PLAYING_CARD_SEVEN_OF_DIAMONDS.svg.png",
  },
  {
    id: 8,
    uniCode: "U+1F0C8",
    htmlCode: "(127176)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/PLAYING_CARD_EIGHT_OF_DIAMONDS.svg/449px-PLAYING_CARD_EIGHT_OF_DIAMONDS.svg.png",
  },
  {
    id: 9,
    uniCode: "U+1F0C9",
    htmlCode: "(127177)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/PLAYING_CARD_NINE_OF_DIAMONDS.svg/449px-PLAYING_CARD_NINE_OF_DIAMONDS.svg.png",
  },
  {
    id: 10,
    uniCode: "U+1F0CA",
    htmlCode: "(127178)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/PLAYING_CARD_TEN_OF_DIAMONDS.svg/449px-PLAYING_CARD_TEN_OF_DIAMONDS.svg.png",
  },
  {
    id: 11,
    uniCode: "U+1F0CB",
    htmlCode: "(127179)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/PLAYING_CARD_JACK_OF_DIAMONDS.svg/449px-PLAYING_CARD_JACK_OF_DIAMONDS.svg.png",
  },
  {
    id: 12,
    uniCode: "U+1F0CD",
    htmlCode: "(127181)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/PLAYING_CARD_QUEEN_OF_DIAMONDS.svg/449px-PLAYING_CARD_QUEEN_OF_DIAMONDS.svg.png",
  },
  {
    id: 13,
    uniCode: "U+1F0CE",
    htmlCode: "(127182)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/PLAYING_CARD_KING_OF_DIAMONDS.svg/449px-PLAYING_CARD_KING_OF_DIAMONDS.svg.png",
  },

  //PLAYING CARD OF CLUBS
  {
    id: 1,
    uniCode: "U+1F0D1",
    htmlCode: "(127185)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/PLAYING_CARD_ACE_OF_CLUBS.svg/449px-PLAYING_CARD_ACE_OF_CLUBS.svg.png",
  },
  {
    id: 2,
    uniCode: "U+1F0D2",
    htmlCode: "(127186)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/PLAYING_CARD_TWO_OF_CLUBS.svg/449px-PLAYING_CARD_TWO_OF_CLUBS.svg.png",
  },
  {
    id: 3,
    uniCode: "U+1F0D3",
    htmlCode: "(127187)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/PLAYING_CARD_THREE_OF_CLUBS.svg/449px-PLAYING_CARD_THREE_OF_CLUBS.svg.png",
  },
  {
    id: 4,
    uniCode: "U+1F0D4",
    htmlCode: "(127188)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/PLAYING_CARD_FOUR_OF_CLUBS.svg/449px-PLAYING_CARD_FOUR_OF_CLUBS.svg.png",
  },
  {
    id: 5,
    uniCode: "U+1F0D5",
    htmlCode: "(127189)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/PLAYING_CARD_FIVE_OF_CLUBS.svg/449px-PLAYING_CARD_FIVE_OF_CLUBS.svg.png",
  },
  {
    id: 6,
    uniCode: "U+1F0D6",
    htmlCode: "(127190)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/PLAYING_CARD_SIX_OF_CLUBS.svg/449px-PLAYING_CARD_SIX_OF_CLUBS.svg.png",
  },
  {
    id: 7,
    uniCode: "U+1F0D7",
    htmlCode: "(127191)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/PLAYING_CARD_SEVEN_OF_CLUBS.svg/449px-PLAYING_CARD_SEVEN_OF_CLUBS.svg.png",
  },
  {
    id: 8,
    uniCode: "U+1F0D8",
    htmlCode: "(127192)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/PLAYING_CARD_EIGHT_OF_CLUBS.svg/449px-PLAYING_CARD_EIGHT_OF_CLUBS.svg.png",
  },
  {
    id: 9,
    uniCode: "U+1F0D9",
    htmlCode: "(127193)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/PLAYING_CARD_NINE_OF_CLUBS.svg/449px-PLAYING_CARD_NINE_OF_CLUBS.svg.png",
  },
  {
    id: 10,
    uniCode: "U+1F0DA",
    htmlCode: "(127194)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/PLAYING_CARD_TEN_OF_CLUBS.svg/449px-PLAYING_CARD_TEN_OF_CLUBS.svg.png",
  },
  {
    id: 11,
    uniCode: "U+1F0DB",
    htmlCode: "(127195)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/PLAYING_CARD_JACK_OF_CLUBS.svg/449px-PLAYING_CARD_JACK_OF_CLUBS.svg.png",
  },
  {
    id: 12,
    uniCode: "U+1F0DD",
    htmlCode: "(127197)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/PLAYING_CARD_QUEEN_OF_CLUBS.svg/449px-PLAYING_CARD_QUEEN_OF_CLUBS.svg.png",
  },
  {
    id: 13,
    uniCode: "U+1F0DE",
    htmlCode: "(127198)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/PLAYING_CARD_KING_OF_CLUBS.svg/449px-PLAYING_CARD_KING_OF_CLUBS.svg.png",
  },
  //PLAYING CARD RED JOKER
  {
    id: 1,
    uniCode: "U+1F0BF",
    htmlCode: "(127167)",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PLAYING_CARD_RED_JOKER.svg/449px-PLAYING_CARD_RED_JOKER.svg.png",
  },
];
